### ISSUE TITLE
What does it mean to be handled by the scheduler differently?

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#21]
>  These will result in the same output, but they are handled by the scheduler differently

**Comment by samueldmcdermott** [comment]
well, one small thing is that the job names will have subscripts according to their $SLURM_ARRAY_TASK_ID value, so the output files will be `slurm_123456789_0.out`, `slurm_123456789_1.out`, etc. rather than `slurm_123456789.out`, `slurm_123456790.out`, `slurm_123456791.out`, etc.

Is that worth saying? It's possible that there are other, more substantive differences, but cluster management and details of slurm I think get pretty intricate and pretty machine-specific pretty fast, so I wouldn't want to say a whole lot more than that

**Comment by samueldmcdermott** [comment]
done
